---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: Sabnzbd
        property: "api key"
    - secretKey: nzb_key
      remoteRef:
        key: Sabnzbd
        property: "nzb key"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd-vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-vpn-secret
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_ENDPOINT_IP
      remoteRef:
        key: Privado VPN
        property: endpoint ip
    - secretKey: WIREGUARD_ENDPOINT_PORT
      remoteRef:
        key: Privado VPN
        property: endpoint port
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: Privado VPN
        property: public key
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Privado VPN
        property: private key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: Privado VPN
        property: address
